blank_issues_enabled: false
contact_links:
  - name: â“ Get Help
    about: Having a hard time with something? Open a question in discussions to get help.
    url: https://github.com/vidstack/player/discussions/new?category=q-a
  - name: ğŸ’¬ Chat
    about: Like to chat with the community about something general? Join our Discord channel.
    url: https://discord.gg/QAjfh2gZE4
