name: Release

on:
  push:
    branches:
      - 'release'
      - 'next'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      # - name: Setup Playwright
      #   run: npx playwright install-deps

      - name: Cache Dependencies
        id: deps
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: deps-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.deps.outputs.cache-hit != 'true'
        run: npm install

      - name: Static Analysis (TS)
        run: npm run types

      - name: Test (UNIT)
        run: npm run test:coverage

      # - name: Test (UNIT)
      #   run: npm run test:ci:coverage

      - name: Analyze (CEM)
        run: npm run analyze

      - name: Submit Coverage Report
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Package
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
